name: Test with Vitest
on: [push, pull_request]
jobs:
  test:
    name: Test and upload coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install
        run: npm i
      - name: Test
        run: npx vitest run
        env:
          CI: true
      - name: Upload coverage to codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: test-results/coverage-final.json
